// Lista de países com códigos de telefone e flags
export const COUNTRIES = [
  { code: "+55", name: "Brasil", flag: "🇧🇷" },
  { code: "+1", name: "EUA", flag: "🇺🇸" },
  { code: "+1", name: "Canadá", flag: "🇨🇦" },
  { code: "+44", name: "Reino Unido", flag: "🇬🇧" },
  { code: "+33", name: "França", flag: "🇫🇷" },
  { code: "+49", name: "Alemanha", flag: "🇩🇪" },
  { code: "+34", name: "Espanha", flag: "🇪🇸" },
  { code: "+39", name: "Itália", flag: "🇮🇹" },
  { code: "+31", name: "Holanda", flag: "🇳🇱" },
  { code: "+32", name: "Bélgica", flag: "🇧🇪" },
  { code: "+43", name: "Áustria", flag: "🇦🇹" },
  { code: "+41", name: "Suíça", flag: "🇨🇭" },
  { code: "+46", name: "Suécia", flag: "🇸🇪" },
  { code: "+45", name: "Dinamarca", flag: "🇩🇰" },
  { code: "+47", name: "Noruega", flag: "🇳🇴" },
  { code: "+358", name: "Finlândia", flag: "🇫🇮" },
  { code: "+353", name: "Irlanda", flag: "🇮🇪" },
  { code: "+30", name: "Grécia", flag: "🇬🇷" },
  { code: "+48", name: "Polônia", flag: "🇵🇱" },
  { code: "+420", name: "Rep. Tcheca", flag: "🇨🇿" },
  { code: "+421", name: "Eslováquia", flag: "🇸🇰" },
  { code: "+36", name: "Hungria", flag: "🇭🇺" },
  { code: "+40", name: "Romênia", flag: "🇷🇴" },
  { code: "+61", name: "Austrália", flag: "🇦🇺" },
  { code: "+64", name: "Nova Zelândia", flag: "🇳🇿" },
  { code: "+81", name: "Japão", flag: "🇯🇵" },
  { code: "+82", name: "Coreia", flag: "🇰🇷" },
  { code: "+65", name: "Singapura", flag: "🇸🇬" },
  { code: "+60", name: "Malásia", flag: "🇲🇾" },
  { code: "+62", name: "Indonésia", flag: "🇮🇩" },
  { code: "+63", name: "Filipinas", flag: "🇵🇭" },
  { code: "+66", name: "Tailândia", flag: "🇹🇭" },
  { code: "+84", name: "Vietnã", flag: "🇻🇳" },
  { code: "+91", name: "Índia", flag: "🇮🇳" },
  { code: "+55", name: "México", flag: "🇲🇽" },
  { code: "+57", name: "Colômbia", flag: "🇨🇴" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+51", name: "Peru", flag: "🇵🇪" },
]

export function getCountryByCode(code: string): { name: string; flag: string } | null {
  return COUNTRIES.find(c => c.code === code) || null
}
