// Lista de países com códigos de telefone
export const COUNTRIES = [
  { code: "+55", name: "Brasil" },
  { code: "+1", name: "Estados Unidos" },
  { code: "+1", name: "Canadá" },
  { code: "+44", name: "Reino Unido" },
  { code: "+33", name: "França" },
  { code: "+49", name: "Alemanha" },
  { code: "+34", name: "Espanha" },
  { code: "+39", name: "Itália" },
  { code: "+31", name: "Holanda" },
  { code: "+32", name: "Bélgica" },
  { code: "+43", name: "Áustria" },
  { code: "+41", name: "Suíça" },
  { code: "+46", name: "Suécia" },
  { code: "+45", name: "Dinamarca" },
  { code: "+47", name: "Noruega" },
  { code: "+358", name: "Finlândia" },
  { code: "+353", name: "Irlanda" },
  { code: "+30", name: "Grécia" },
  { code: "+48", name: "Polônia" },
  { code: "+420", name: "República Tcheca" },
  { code: "+421", name: "Eslováquia" },
  { code: "+36", name: "Hungria" },
  { code: "+40", name: "Romênia" },
  { code: "+359", name: "Bulgária" },
  { code: "+385", name: "Croácia" },
  { code: "+381", name: "Sérvia" },
  { code: "+386", name: "Eslovênia" },
  { code: "+371", name: "Letônia" },
  { code: "+372", name: "Estônia" },
  { code: "+370", name: "Lituânia" },
  { code: "+61", name: "Austrália" },
  { code: "+64", name: "Nova Zelândia" },
  { code: "+81", name: "Japão" },
  { code: "+82", name: "Coreia do Sul" },
  { code: "+886", name: "Taiwan" },
  { code: "+65", name: "Singapura" },
  { code: "+60", name: "Malásia" },
  { code: "+62", name: "Indonésia" },
  { code: "+63", name: "Filipinas" },
  { code: "+66", name: "Tailândia" },
  { code: "+84", name: "Vietnã" },
  { code: "+852", name: "Hong Kong" },
  { code: "+853", name: "Macau" },
  { code: "+886", name: "Taiwan" },
  { code: "+91", name: "Índia" },
  { code: "+92", name: "Paquistão" },
  { code: "+93", name: "Afeganistão" },
  { code: "+94", name: "Sri Lanka" },
  { code: "+95", name: "Mianmar" },
  { code: "+98", name: "Irã" },
  { code: "+359", name: "Bulgária" },
]

export function getCountryByCode(code: string): string {
  const country = COUNTRIES.find(c => c.code === code)
  return country?.name || code
}
